package entity;
// Generated 18/03/2020 02:58:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer idGroup;
     private String groupName;
     private String grupoKey;
     private Set users = new HashSet(0);
     private Set courses = new HashSet(0);

    public Group() {
    }

	
    public Group(String groupName, String grupoKey) {
        this.groupName = groupName;
        this.grupoKey = grupoKey;
    }
    public Group(String groupName, String grupoKey, Set users, Set courses) {
       this.groupName = groupName;
       this.grupoKey = grupoKey;
       this.users = users;
       this.courses = courses;
    }
   
    public Integer getIdGroup() {
        return this.idGroup;
    }
    
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getGrupoKey() {
        return this.grupoKey;
    }
    
    public void setGrupoKey(String grupoKey) {
        this.grupoKey = grupoKey;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


